#!/usr/bin/env bash

IMAGE="netsells-cli"
VERSION="1"

DOCKER_IMAGE="$IMAGE:$VERSION"

error(){
  error_code=$1
  echo "ERROR: $2" >&2
  exit $1
}

# Check for docker
which docker > /dev/null 2>&1 || error 1 "docker not found!"

if [[ $1 == "self-update" ]]
then
    docker pull $DOCKER_IMAGE

    docker run \
        --rm \
        --init \
        --entrypoint=/bin/cat \
        $DOCKER_IMAGE \
        /usr/local/bin/netsells-wrapper > $0

    exit 0
fi

exec docker run \
    --rm \
    --init \
    -it \
    -v $(pwd):/app \
    -v ~/.ssh:/root/.ssh \
    -v ~/.aws:/root/.aws \
    -v /var/run/docker.sock:/var/run/docker.sock \
    $DOCKER_IMAGE "$@"
