#!/usr/bin/env bash

IMAGE="netsells/cli"
VERSION="dev-docker-wrapper"

DOCKER_IMAGE="$IMAGE:$VERSION"

error(){
  error_code=$1
  echo "We had a problem! $2" >&2
  exit $1
}

# Check for docker
which docker > /dev/null 2>&1 || error 1 "🐳 Docker was not found! Please install it and try again."

if [[ $1 == "self-update" ]]
then
    echo -e "\033[0;31mUpdating CLI docker image...\033[0m"
    docker pull $DOCKER_IMAGE

    echo -e "\033[0;31mUpdating CLI wrapper...\033[0m"
    sudo sh -c "docker run \
        --rm \
        --init \
        --entrypoint=/bin/cat \
        $DOCKER_IMAGE \
        /usr/local/bin/netsells-wrapper > $0"

    echo -e "\033[0;31mDone!\033[0m"

    exit 0
fi

exec docker run \
    --rm \
    --init \
    -it \
    -v $(pwd):/app \
    -v ~/.aws:/root/.aws:ro \
    -v /var/run/docker.sock:/var/run/docker.sock \
    $DOCKER_IMAGE "$@"
