name: Debug Release

on: push

env:
  COMPOSER_FLAGS: "--ansi --no-interaction --no-progress --no-suggest --prefer-dist"

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::v1.0.4
      - name: Checkout code
        uses: actions/checkout@v2

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          extensions: "intl"
          ini-values: "memory_limit=-1"
          php-version: "7.4"

      - name: "Install dependencies from composer.lock using composer binary provided by system"
        run: "composer install ${{ env.COMPOSER_FLAGS }}"


      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v2

      - name: Build Release
        run: php netsells app:build --build-version=${{ steps.get_version.outputs.VERSION }}